CREATE TABLE TBUsers (
UUID_Users NVARCHAR2(50) PRIMARY KEY,
Name NVARCHAR2(100) NOT NULL,
NameUser NVARCHAR2(100) NOT NULL,
Password NVARCHAR2(20) NOT NULL
);

-- Patients = Pacientes
CREATE TABLE TBPatients(
UUID_Patients NVARCHAR2(50) PRIMARY KEY,
Name NVARCHAR2(50) NOT NULL,
LastName NVARCHAR2(50) NOT NULL,
Age INT NOT NULL, 
Disease NVARCHAR2(100) NOT NULL,
RoomNumber INT NOT NULL,
BedNumber INT NOT NULL,
Medication NVARCHAR2(200) NOT NULL,
AddmissionDate NVARCHAR2(10) NOT NULL,
MedicationTime NVARCHAR2(10) NOT NULL
);
